# Currently fixing bug with docker compose
version: "3.8"

services:
  backend:
    platform: linux/amd64
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - 4000:4000
    networks:
      - my_network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  backend:
  frontend:
