-- CreateTable
CREATE TABLE "Sleep" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sleepDuration" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,
    "sleptAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Sleep_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
